spring.application.name=demo

# Conexión principal (usando variables de entorno)
spring.datasource.url=jdbc:postgresql://dpg-d7oa9i9j2pic739o1vg0-a.virginia-postgres.render.com:5432/bd_prog4_salgado
spring.datasource.username=bd_prog4_salgado_user
spring.datasource.password=usNb0HzwQioJ1wmq3A8trWCQ5LHoxLIO

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para optimizar consultas a PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect